[package]
name = "link-protocol-binser"
description = "The Oro Link protocol 'binser' serializer"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = { version = "0.3.5", default-features = false, optional = true }
link-protocol-binser-proc = { path = "../link-protocol-binser-proc" }
