[package]
name = "link-daemon"
description = "Oro Link broker daemon for CI/CD"
publish = false
edition = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[[bin]]
name = "link-daemon"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
env_logger = "0.11.10"
log = "0.4.29"
rustls = "0.23.37"
rustls-pemfile = "2.2.0"
tokio = { version = "1.50.0", features = ["io-util", "macros", "net", "rt-multi-thread", "signal", "time"] }
tokio-rustls = "0.26.4"
x509-parser = "0.16.0"
mqtt-async-client = { version = "0.3.1", default-features = false }
