[package]
name = "link-area-daemon"
description = "Area controller daemon for Oro Links within the same LAN"
publish = false
edition = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[[bin]]
name = "link-aread"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
anyhow = "1.0.102"
tokio = { version = "1.50.0", features = ["rt-multi-thread", "macros", "fs", "time", "net", "io-util", "signal", "sync"] }
log = "0.4.29"
env_logger = "0.11.10"
toml = "1.1.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_plain = "1.0.2"
mdns-sd = { version = "0.18.2", features = ["log"] }
rustls = "0.23.37"
rustls-pemfile = "2.2.0"
tokio-rustls = "0.26.4"
x509-parser = "0.16.0"
