[package]
name = "link-firmware"
description = "Oro Link firmware"
publish = false
edition = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
version = { workspace = true }

build = "build.rs"

[dependencies]
link-protocol = { path = "../link-protocol", features = ["defmt", "embedded-io", "embassy"] }
cortex-m-rt = "0.7.3"
defmt = { version = "1.0.1", default-features = false }

embedded-graphics = { version = "0.8.0" }
embedded-graphics-core = "0.4.0"
embedded-graphics-framebuf = "0.5.0"
embedded-hal = "1.0.0-alpha.11"
embedded-hal-bus = { version = "0.2.0", features = ["async"] }
embedded-hal-async = "1.0.0"
heapless = "0.8"
micromath = "2.0.0"
static_cell = { version = "2.0.0", features = ["nightly"] }

defmt-rtt = "0.4.0"
stm32-metapac = { version = "14.0.0", features = ["stm32f479vg"] }
sha2 = { version = "0.10.7", default-features = false, features = ["asm-aarch64"] }
rand_core = "0.6.4"
embedded-io-async = "0.6.1"
embassy-sync = { git = "https://github.com/oro-os/dep.embassy.git" }
embassy-futures = { git = "https://github.com/oro-os/dep.embassy.git" }
panic-probe = "1.0.0"
# XXX DEBUG: This is just to test USB connectivity.
usbd-hid = "0.8.2"

[dependencies.oro-logo-rle]
git = "https://github.com/oro-os/oro-logo-rle"
default-features = false
features = ["oro-logo-64"]

[dependencies.embassy-net-wiznet]
version = "0.2.0"
git = "https://github.com/oro-os/dep.embassy.git"
features = ["defmt"]

[dependencies.cortex-m]
version = "0.7.7"
features = [
	"critical-section-single-core",
	"inline-asm"
]

[dependencies.embassy-executor]
git = "https://github.com/oro-os/dep.embassy.git"
features = [
	"arch-cortex-m",
	"executor-thread",
]

[dependencies.embassy-time]
git = "https://github.com/oro-os/dep.embassy.git"
features = [
	"tick-hz-32_768"
]

[dependencies.embassy-stm32]
git = "https://github.com/oro-os/dep.embassy.git"
features = [
	"stm32f479vg",
	"defmt",
	"unstable-pac",
	"time-driver-any",
	"exti",
	"single-bank"
]

[dependencies.embassy-net]
git = "https://github.com/oro-os/dep.embassy.git"
features = [
	"defmt",
	"tcp",
	"udp",
	"dns",
	"dhcpv4",
	"proto-ipv4",
	"proto-ipv6",
	"medium-ethernet"
]

[dependencies.embassy-usb]
git = "https://github.com/oro-os/dep.embassy.git"
features = [
	"defmt",
	"usbd-hid",
	"max-interface-count-2",
]

[dependencies.embassy-embedded-hal]
git = "https://github.com/oro-os/dep.embassy.git"
features = [
	"defmt",
]


[dependencies.smoltcp]
version = "0.11.0"
default-features = false
features = [
	"medium-ethernet",
	"defmt",
	"packetmeta-id",
	"async",
	"proto-igmp",
	"proto-dhcpv4",
	"proto-ipv4-fragmentation",
	"proto-dns",
	"proto-ipv4",
	"socket-icmp",
	"socket-udp",
	"socket-tcp",
	"socket-dhcpv4",
	"socket-dns",
	"socket-dns",
	"iface-max-multicast-group-count-3",
	"dns-max-server-count-2"
]

[build-dependencies]
pixglyph = "0.1.0"
png = "0.17.9"
proc-macro2 = "1.0.66"
quote = "1.0.32"
syn = { version = "2.0.28", features = ["full"] }
ttf-parser = "0.18.0"
