[package]
name = "link-firmware"
description = "Oro Link firmware"
publish = false
edition = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
version = { workspace = true }

build = "build.rs"

[features]
default = []
bank1 = []
bank2 = []

[dependencies]
link-protocol = { path = "../link-protocol", features = ["defmt", "embedded-io", "embassy"] }
cortex-m-rt = "0.7.3"
defmt = { version = "1.0.1", default-features = false }

embedded-graphics = { version = "0.8.0" }
embedded-graphics-core = "0.4.0"
embedded-graphics-framebuf = "0.5.0"
embedded-hal = "1.0.0-alpha.11"
embedded-hal-bus = { version = "0.2.0", features = ["async"] }
embedded-hal-async = "1.0.0"
embassy-net-wiznet = { version = "0.2.1", features = ["defmt"] }
embassy-executor = { version = "0.9.1", features = [ "arch-cortex-m", "executor-thread" ] }
embassy-time = { version = "0.5.0", features = ["tick-hz-32_768"] }
embassy-sync = "0.7.2"
embassy-futures = "0.1.2"
embassy-stm32 = { version = "0.4.0", features = [ "stm32f479vg", "defmt", "unstable-pac", "time-driver-any", "exti", "single-bank" ] }
embassy-net = { version = "0.7.1", features = [ "defmt", "tcp", "udp", "dns", "dhcpv4", "proto-ipv4", "proto-ipv6", "medium-ethernet" ] }
embassy-usb = { version = "0.5.1", features = [ "defmt", "usbd-hid", "max-interface-count-2" ] }
embassy-embedded-hal = { version = "0.5.0", features = ["defmt"] }
heapless = { version = "0.9.2", features = ["defmt"] }
micromath = "2.0.0"
static_cell = { version = "2.0.0", features = ["nightly"] }
defmt-rtt = "0.4.0"
stm32-metapac = { version = "14.0.0", features = ["stm32f479vg"] }
sha2 = { version = "0.10.7", default-features = false, features = ["asm-aarch64"] }
rand_core = "0.6.4"
embedded-io-async = "0.6.1"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
cortex-m = { version = "0.7.7", features = ["critical-section-single-core", "inline-asm"] }
# XXX DEBUG: This is just to test USB connectivity.
usbd-hid = "0.8.2"
embedded-storage = "0.3.1"
crc32fast = { version = "1.5.0", default-features = false }

[dependencies.oro-logo-rle]
git = "https://github.com/oro-os/oro-logo-rle"
default-features = false
features = ["oro-logo-64"]

[dependencies.smoltcp]
version = "0.12.0"
default-features = false
features = [
	"medium-ethernet",
	"defmt",
	"packetmeta-id",
	"async",
	"proto-dhcpv4",
	"proto-ipv4-fragmentation",
	"proto-dns",
	"proto-ipv4",
	"socket-icmp",
	"socket-udp",
	"socket-tcp",
	"socket-dhcpv4",
	"socket-dns",
	"socket-dns",
	"iface-max-multicast-group-count-3",
	"dns-max-server-count-2"
]

[build-dependencies]
pixglyph = "0.1.0"
png = "0.17.9"
proc-macro2 = "1.0.66"
quote = "1.0.32"
syn = { version = "2.0.28", features = ["full"] }
ttf-parser = "0.18.0"
