[package]
name = "link-cli"
description = "CLI for interacting with a Link over the MINIE serial device"
publish = false
edition = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
link-protocol = { path = "../link-protocol", features = ["std"] }

clap = { version = "4.5.60", features = ["derive"] }
serial = "0.4.0"
anyhow = "1.0.102"
static_cell = { version = "2.0.0", features = ["nightly"] }
