[package]
name = "oro-link-firmware"
version = { workspace = true }
publish = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[lib]
path = "src/lib.rs"
test = false
bench = false

[dev-dependencies]
rusty-hook = "0.11.2"
