[package]
name = "oro-link-firmware"
description = "Oro Link firmware"
version = "0.0.0"
publish = false
edition = "2021"
authors = [ "Joshua Lee Junon <junon@oro.sh> (https://github.com/qix-)" ]
repository = "https://github.com/oro-os/oro-link-x86"
license = "MIT"
resolver = "2"

[features]
default = []

# Supported uC's
# NOTE: one uC model == one board variant.
stm32f479vg = [
	"stm32",
	"embassy-stm32/stm32f479vg",
	"is31fl3218"
]

# Supported peripheral chips
# NOTE: don't use directly; only meant to be used by uC features
is31fl3218 = []

# Chip types
# NOTE: don't use directly; only meant to be used by uC features
cortex-m = [
	"dep:cortex-m",
	"cortex-m-rt",
	"embassy-executor/arch-cortex-m"
]
stm32 = [
	"cortex-m",
	"embassy-stm32",
]

[dependencies]
cortex-m-rt = { version = "0.7.3", optional = true }

[dependencies.cortex-m]
version = "0.7.7"
optional = true
features = [
	"critical-section-single-core",
	"inline-asm"
]

[dependencies.embassy-executor]
git = "https://github.com/embassy-rs/embassy"
features = [
	"nightly",
	"integrated-timers",
	"executor-thread"
]

[dependencies.embassy-time]
git = "https://github.com/embassy-rs/embassy"
features = [
	"nightly",
	"unstable-traits",
	"tick-hz-32_768"
]

[dependencies.embassy-stm32]
optional = true
git = "https://github.com/embassy-rs/embassy"
features = [
	"nightly",
	"unstable-traits",
	"unstable-pac",
	"time-driver-any"
]

[profile.release]
opt-level = 3       # Maximum optimizations
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
# FIXME: For some reason, this causes the firmware not to boot.
#lto = "fat"        # Perform LTO across all crates
