[package]
name = "oro-link-firmware"
description = "Oro Link firmware"
version = "0.0.0"
publish = false
edition = "2021"
authors = [ "Joshua Lee Junon <junon@oro.sh> (https://github.com/qix-)" ]
repository = "https://github.com/oro-os/oro-link-x86"

[features]
default = []

# supported platforms
stm32f479 = [
	"stm32f4xx-hal",
	"stm32f4xx-hal/stm32f479",
	"is31fl3218",
	"enc28j60",
	"smoltcp/iface-max-addr-count-2",
	"smoltcp/iface-max-multicast-group-count-2",
	"smoltcp/iface-neighbor-cache-count-4",
	"smoltcp/iface-max-route-count-2",
	"smoltcp/fragmentation-buffer-size-2048",
	"smoltcp/assembler-max-segment-count-8",
	"smoltcp/reassembly-buffer-size-2048",
	"smoltcp/reassembly-buffer-count-2",
	"smoltcp/dns-max-result-count-1",
	"smoltcp/dns-max-server-count-1",
	"smoltcp/dns-max-name-size-64"
]

# common peripherals
is31fl3218 = []
enc28j60 = ["dep:enc28j60", "embedded-hal"]

[dependencies]
embedded-hal = { version = "0.2.7", optional = true }
enc28j60 = { version = "0.3.0", optional = true, git = "https://github.com/oro-os/enc28j60", features = [ "smoltcp" ] }
stm32f4xx-hal = { version = "0.17.1", optional = true }

[dependencies.smoltcp]
version = "0.10.0"
default-features = false
features = [
	"medium-ethernet",
	"medium-ip",
	"proto-dhcpv4",
	"proto-dns",
	"proto-igmp",
	"proto-ipv4",
	"proto-ipv4-fragmentation",
	"proto-ipv6",
	"socket",
	"socket-dhcpv4",
	"socket-dns",
	"socket-icmp",
	"socket-raw",
	"socket-tcp",
	"socket-udp"
]

[dev-dependencies]
rusty-hook = "0.11.2"

[profile.release]
opt-level = 3       # Maximum optimizations
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
# FIXME: For some reason, this causes the firmware not to boot.
#lto = "fat"        # Perform LTO across all crates
