[workspace.package]
version = "0.0.0"
publish = false
edition = "2021"
authors = [ "Joshua Lee Junon <junon@oro.sh> (https://github.com/qix-)" ]
repository = "https://github.com/oro-os/oro-link-x86"

[workspace]
resolver = "2"
members = [
	"src/oro-link-firmware",
	"src/oro-link-stm32f7"
]

[profile.release]
opt-level = 3       # Maximum optimizations
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
# FIXME: For some reason, this causes the firmware not to boot.
#lto = "fat"        # Perform LTO across all crates
